version: "3.9"

services:
  db:
    image: mysql:latest
    volumes:
      - db-vol:/var/lib/mysql
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpwd
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=familytree

  node:
    image: familytreenode
    build: ./backend-node
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - DB_HOST=db
      - DB_USERNAME=admin
      - DB_PASSWORD=adminpwd
      - DB_DATABASE=familytree
      - DB_DIALECT=mysql
      - DB_PORT=3306
    depends_on:
      - db

  # spring:
  #   image: familytreespring
  #   build: ./backend-spring
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  frontend:
    image: front
    build: ./frontend
    ports:
      - 8081:80
    depends_on:
      - node

volumes:
  db-vol:
