-- MySQL Script generated by MySQL Workbench
-- Sat Jul 23 16:05:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema familytree
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `familytree` ;

-- -----------------------------------------------------
-- Schema familytree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `familytree` DEFAULT CHARACTER SET utf8 ;
USE `familytree` ;

-- -----------------------------------------------------
-- Table `familytree`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`member` (
  `id` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `birthday` DATE NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`family` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `notes` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`relation` (
  `id` VARCHAR(50) NOT NULL,
  `first_member_id` VARCHAR(50) NOT NULL,
  `second_member_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relation_member_second_idx` (`second_member_id` ASC) VISIBLE,
  INDEX `fk_relation_member_fisrt_idx` (`first_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_relation_member_fisrt`
    FOREIGN KEY (`first_member_id`)
    REFERENCES `familytree`.`family_members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_relation_member_second`
    FOREIGN KEY (`second_member_id`)
    REFERENCES `familytree`.`family_members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`family_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`family_members` (
  `id` VARCHAR(50) NOT NULL,
  `member_id` VARCHAR(50) NOT NULL,
  `family_id` VARCHAR(50) NOT NULL,
  `union_date` DATE NOT NULL,
  `rel_parent_id` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_family_members_family_idx` (`family_id` ASC) VISIBLE,
  INDEX `fk_family_members_member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_family_members_relation_idx` (`rel_parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_family_members_family`
    FOREIGN KEY (`family_id`)
    REFERENCES `familytree`.`family` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_members_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `familytree`.`member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_members_relation`
    FOREIGN KEY (`rel_parent_id`)
    REFERENCES `familytree`.`relation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `familytree`.`member`
-- -----------------------------------------------------
START TRANSACTION;
USE `familytree`;
INSERT INTO `familytree`.`member` (`id`, `description`, `birthday`, `avatar`) VALUES ('6698b5d1-f2eb-4656-8036-0bb259b256f7', 'Lucino', '1922-04-20', '');
INSERT INTO `familytree`.`member` (`id`, `description`, `birthday`, `avatar`) VALUES ('92286c71-89eb-47ca-a40e-2e0ed635f2f9', 'Ernestina', '1934-05-18', '');
INSERT INTO `familytree`.`member` (`id`, `description`, `birthday`, `avatar`) VALUES ('caff2cf0-9478-417b-9170-f41c6b48a334', 'Samuel', '1969-08-17', '');

COMMIT;


-- -----------------------------------------------------
-- Data for table `familytree`.`family`
-- -----------------------------------------------------
START TRANSACTION;
USE `familytree`;
INSERT INTO `familytree`.`family` (`id`, `name`, `notes`) VALUES ('d5ca8bc3-49de-423d-a4e3-b8f1cc2ef600', 'Baez', 'Familia Baez');

COMMIT;


-- -----------------------------------------------------
-- Data for table `familytree`.`relation`
-- -----------------------------------------------------
START TRANSACTION;
USE `familytree`;
INSERT INTO `familytree`.`relation` (`id`, `first_member_id`, `second_member_id`) VALUES ('2bc9f9bd-ba84-4388-914d-9c31bbcbbe3d', '4041a99b-c553-4144-859b-763b64b71955', '71a5683e-be1c-4e89-8185-aba885efa328');

COMMIT;


-- -----------------------------------------------------
-- Data for table `familytree`.`family_members`
-- -----------------------------------------------------
START TRANSACTION;
USE `familytree`;
INSERT INTO `familytree`.`family_members` (`id`, `member_id`, `family_id`, `union_date`, `rel_parent_id`) VALUES ('4041a99b-c553-4144-859b-763b64b71955', '6698b5d1-f2eb-4656-8036-0bb259b256f7', 'd5ca8bc3-49de-423d-a4e3-b8f1cc2ef600', '2022-07-23', NULL);
INSERT INTO `familytree`.`family_members` (`id`, `member_id`, `family_id`, `union_date`, `rel_parent_id`) VALUES ('71a5683e-be1c-4e89-8185-aba885efa328', '92286c71-89eb-47ca-a40e-2e0ed635f2f9', 'd5ca8bc3-49de-423d-a4e3-b8f1cc2ef600', '2022-07-23', NULL);
INSERT INTO `familytree`.`family_members` (`id`, `member_id`, `family_id`, `union_date`, `rel_parent_id`) VALUES ('13206be3-a2a5-43da-a373-ec02423da863', 'caff2cf0-9478-417b-9170-f41c6b48a334', 'd5ca8bc3-49de-423d-a4e3-b8f1cc2ef600', '2022-07-23', '2bc9f9bd-ba84-4388-914d-9c31bbcbbe3d');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
