-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 12:20:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema familytree
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `familytree` ;

-- -----------------------------------------------------
-- Schema familytree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `familytree` DEFAULT CHARACTER SET utf8 ;
USE `familytree` ;

-- -----------------------------------------------------
-- Table `familytree`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`member` (
  `id` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `birthday` DATE NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`family` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `notes` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`relation` (
  `id` VARCHAR(50) NOT NULL,
  `first_member_id` VARCHAR(50) NOT NULL,
  `second_member_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_relation_member_second_idx` (`second_member_id` ASC) VISIBLE,
  INDEX `fk_relation_member_fisrt_idx` (`first_member_id` ASC) VISIBLE,
  CONSTRAINT `fk_relation_member_fisrt`
    FOREIGN KEY (`first_member_id`)
    REFERENCES `familytree`.`family_members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_relation_member_second`
    FOREIGN KEY (`second_member_id`)
    REFERENCES `familytree`.`family_members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `familytree`.`family_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `familytree`.`family_members` (
  `id` VARCHAR(50) NOT NULL,
  `member_id` VARCHAR(50) NOT NULL,
  `family_id` VARCHAR(50) NOT NULL,
  `union_date` DATE NOT NULL,
  `rel_parent_id` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_family_members_family_idx` (`family_id` ASC) VISIBLE,
  INDEX `fk_family_members_member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_family_members_relation_idx` (`rel_parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_family_members_family`
    FOREIGN KEY (`family_id`)
    REFERENCES `familytree`.`family` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_members_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `familytree`.`member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_family_members_relation`
    FOREIGN KEY (`rel_parent_id`)
    REFERENCES `familytree`.`relation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
